import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { SupabaseListener } from '../components/supabase-listener';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <SupabaseListener />
      <body className={`bg-gray-100 ${inter.className}`}>{children}</body>
    </html>
  );
}